### ISSUE TITLE
hello, please I need a little help here when I try to update the presale it shows CONTRACT FROZEN I don't know why.

### ISSUE THREAD

**Issue by lizee78** [codeSTACKr/minter-dapp#1]

**Comment by thepeanutgalleryandco** [comment]
Your contract is only frozen if you set it into a frozen state on creation or one of the updates.

**Comment by lizee78** [comment]
Please  how can I remove it from a frozen state ?

**Comment by codeSTACKr** [comment]
Once frozen it cannot be undone.
