### ISSUE TITLE
[Bug]: Frontend Landing Page - "spinner" always on and "coundown card" not loading.

### ISSUE THREAD

**Issue by FUCryptoClub** [codeSTACKr/minter-dapp#106]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

I have successfully deployed my site to netlify after completing all backend steps.

I have not made any changes to the frontend except the 'const contractAddress' as per the video tutorial.

The issue I am faced with is that when opening my site the 'spinner' is constantly spinning/loading and the 'countdown card' does not appear in any capacity, there is no welcome message, nor countdown or minting options. See screenshots below:
<img width="1440" alt="Forever-load" src="https://user-images.githubusercontent.com/110253844/182022329-b3fc7d33-d845-4168-a8cd-5da4898e4df2.png">

I can connect to Metamask without issues. But unable to test my pre-sale/open sale due to the 'countdown card' not showing.

I appreciate the help in advance.

### What have you tried?

I Googled and asked the community in the discord server but could not find a solution.

### Protect your information

- [X] I Agree

**Comment by FUCryptoClub** [comment]
The opening message seems to appear on Firefox, but then when I connect my wallet, the infamous never-ending spinner is present.
<img width="1422" alt="Screenshot 2022-07-31 at 19 33 35" src="https://user-images.githubusercontent.com/110253844/182038557-f10b738f-3b4e-44db-84c0-2fea57ab45d7.png">

**Comment by Vonnie187** [comment]
yes i'm having the same issue in Brave browser, never ending spinner

**Comment by FUCryptoClub** [comment]
I've been trying to get my head around this issue to no avail. Please forgive me, I am not a coder.

I have noticed that certain class names are not being included the class=""

for example. when I visit my site in a browser and inspect element I can see the section class as follows:

`<section class="container not-connected">`

Whereas on cbirdz.xyz the section class is as follows:

`<section class="container not-connected show-not-connected">`

The "show-not-connected" class is not applied. Although it is applied in Firefox, but then when I connect my wallet, I am presented with the wheel of death.

I assume this must be an issue with .js in some capacity.

It would be great if we can have some feedback so we can come to a solution and conclusion.

**Comment by Vonnie187** [comment]
they have said, in discord from about 10 different people that it is the abi,js file..

the best way they said;

go to nftport > docs > user > get contract abi
then in the panel on the right > input your api key > contract > then hit the api fetch button.

In the code sample is you abi copy all and past this one in the front end abi.js

then push it to ur repo and its supposed to work....

not for me, 3 days later i'm rebuilding from scratch just incase i stuffed up early, my stuff looks better now lol but i'm not at the deploy new contract yet, i'll update if this new abi works

**Comment by Vonnie187** [comment]
oh in that panel put the chain your contract was on "rinkeby" etc etc

**Comment by FUCryptoClub** [comment]
I've tried all this. Still nothing. I'll be interested to know if starting from scratch works. If I find a solution I'll update.

**Comment by Vonnie187** [comment]
yeah it all worked great until the presale timer stopped, instead of going to to presale minting its stuck again on that loading page, its like the mint window is set to hidden or 0 something is not calling it and i know its not just the abi, ive given it too many hours i'll come back to it another time

**Comment by FUCryptoClub** [comment]
I've also tried deleting some scripts such as the splide.min.js to see if this interferes.

I've tried deleting the abi.js and including it in the contstants.js such as the earlier versions.

Has opens released an update which no longer corresponds to the code in the .js files... I'm at a loss... any ideas @codeSTACKr

**Comment by FUCryptoClub** [comment]
Oh and there seems to be a layout issue where the "welcome" <div> has most of its content cut off and not aligned with the splide. Minor issue

**Comment by FUCryptoClub** [comment]
> yeah it all worked great until the presale timer stopped, instead of going to to presale minting its stuck again on that loading page, its like the mint window is set to hidden or 0 something is not calling it and i know its not just the abi, ive given it too many hours i'll come back to it another time

Just did the whole process from scratch and arrived at the same point as you this time. Once connected to wallet, the presale mint window appeared (which it didn't before) then when changing the date to a date and time in the past, I am again faced with the wheel of death. Losing hope.

**Comment by Vonnie187** [comment]
I have since moved on, unfortunately I have a mint deadline

**Comment by Vonnie187** [comment]
I will find a way to make it work once I have learnt more, Its frustrating not knowing how to fix stuff yet but they did say no coding needed lol

**Comment by MrLajawab19** [comment]
> ### Version
> * [x]  Yes
> 
> ### General Question
> * [x]  No
> 
> ### What happened?
> I have successfully deployed my site to netlify after completing all backend steps.
> 
> I have not made any changes to the frontend except the 'const contractAddress' as per the video tutorial.
> 
> The issue I am faced with is that when opening my site the 'spinner' is constantly spinning/loading and the 'countdown card' does not appear in any capacity, there is no welcome message, nor countdown or minting options. See screenshots below: <img alt="Forever-load" width="1440" src="https://user-images.githubusercontent.com/110253844/182022329-b3fc7d33-d845-4168-a8cd-5da4898e4df2.png">
> 
> I can connect to Metamask without issues. But unable to test my pre-sale/open sale due to the 'countdown card' not showing.
> 
> I appreciate the help in advance.
> 
> ### What have you tried?
> I Googled and asked the community in the discord server but could not find a solution.
> 
> ### Relevant log output
> _No response_
> 
> ### Protect your information
> * [x]  I Agree
go to your backend folder  > go to build > go to contract >go to contract_abi.json............copy all > go to frontend >go to js >go to abi.js.......paste here.
now sync your changes ......
(If doesnt work try to deploy a new contract again and then try these steps)
now the countdown card will appear  but when countdown gets over it will start spinning/loading again ...............dont know what to do next.
