### ISSUE TITLE
unable to generate images

### ISSUE THREAD

**Issue by KristophTahti** [codeSTACKr/minter-dapp#11]
I have zero coding experience.

Getting an error when I try to generate, 
PS D:\NFT\minter-dapp\backend> npm run generate

> minter-dapp-backend@0.0.2 generate
> node index.js

(node:13604) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1392
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'D:\NFT\minter-dapp\backend/layers/Background/'
    at Object.readdirSync (node:fs:1392:3)
    at getElements (D:\NFT\minter-dapp\backend\src\main.js:73:6)
    at D:\NFT\minter-dapp\backend\src\main.js:89:15
    at Array.map (<anonymous>)
    at startCreating (D:\NFT\minter-dapp\backend\src\main.js:349:20)
    at D:\NFT\minter-dapp\backend\index.js:6:3
    at Object.<anonymous> (D:\NFT\minter-dapp\backend\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'D:\\NFT\\minter-dapp\\backend/layers/Background/'

Would appreciate any advice.

**Comment by KristophTahti** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/93036559/161400444-4d1be01a-b4cb-467d-a1e8-d21a0c668797.png)

**Comment by cristiane13091991** [comment]
I have the same situation. I got this when I execute: npm run generate

PS D:\NFT Projects\Baby Galapagos Club\Programacion\minter-dapp-main> npm run generate
npm ERR! Missing script: "generate"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Local\npm-cache\_logs\2022-04-03T04_37_09_983Z-debug-0.log

**Comment by ericksommet** [comment]
I had the same issue and to solve it I desinstalled completely Visual Code and Node Js and reinstalled it fresh.   
It is very important to make a clean uninstall like in this link:  
https://code.visualstudio.com/docs/setup/uninstall 
or you will find your old project anew and the same problems.

**Comment by YOGAPAARTIBAN** [comment]
Earlier their were no issues with this command.

Now it comes with the following error

> minter-dapp-backend@0.0.2 generate
> node index.js

(node:7892) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\Dell\Desktop\RedLayers\minter-dapp\backend\src\main.js:181
    const image = await loadImage(`${_layer.selectedElement.path}`);
                                                            ^

TypeError: Cannot read properties of undefined (reading 'path')
    at C:\Users\Dell\Desktop\RedLayers\minter-dapp\backend\src\main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Dell\Desktop\RedLayers\minter-dapp\backend\src\main.js:180:10)
    at C:\Users\Dell\Desktop\RedLayers\minter-dapp\backend\src\main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\Dell\Desktop\RedLayers\minter-dapp\backend\src\main.js:360:17)
    at C:\Users\Dell\Desktop\RedLayers\minter-dapp\backend\index.js:6:3
    at Object.<anonymous> (C:\Users\Dell\Desktop\RedLayers\minter-dapp\backend\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)

Anyone have any idea to solve this?

**Comment by codeSTACKr** [comment]
The `path` issue is a result of either your configuration not being correct, not saved, or your layer folder/file names containing special characters. For the names, you should only use a-z, 0-1, and spaces. Do not use dashes, slashes, or any other special characters.
