### ISSUE TITLE
Unable to deploy at the frontend.

### ISSUE THREAD

**Issue by MarkHButler** [codeSTACKr/minter-dapp#13]
Hi there; I am unable to deploy to the website. Changes like the sidebar, colors aren't being reflected in the site. I am also unable to connect MetaMask, a connection gif just keeps scolling. I think I have been accurate in following your instructions but I did notice 2 things: right at the beginning in source control I didnt have the feature to clone so used the zip. folder for minter.dapp in my hashlips folder and executed from there;
![image](https://user-images.githubusercontent.com/94656204/161415647-60c0e9cf-7c44-499f-ab55-d1997a12db5c.png) and I havent had the option to synch in source control though I can commit; my option is always publish branch:
![image](https://user-images.githubusercontent.com/94656204/161415724-9f39d292-3e7e-4bb4-b194-cfcb5e530d9d.png)

![image](https://user-images.githubusercontent.com/94656204/161471686-fb528af4-8b1e-4dd8-9384-ae59b4f27281.png)

**Comment by codeSTACKr** [comment]
Most likely this is a Netlify configuration issue. Be sure you have set the base path to `frontend` and added your API key to the Netlify secrets (environment variable).
