### ISSUE TITLE
I want to reveal the token image after minting/purchase in a public sale.

### ISSUE THREAD

**Issue by edhellerdotcom** [codeSTACKr/minter-dapp#14]
Hello codeSTACKr team!

I'm looking for a way to run the "npm run update_base_uri" script automatically after a token is purchased/minted in a public sale.

Does anyone know where I can add this code?

p.s. - This repository is great!

**Comment by krupis** [comment]
I also have this issue. I have purchased 2 NFT's during presale and had to run the command "npm run update_base_uri" to reveal the NFT's. However, I have changed the date and started a public sale, now any sold NFT's should be automatically revealed according to the guide video but mine shows unrevealed:
![image](https://user-images.githubusercontent.com/22237034/162020909-e55d31df-c15e-42d1-b294-7abcf42e3854.png)

**Comment by edhellerdotcom** [comment]
In config.js, if you change the line that says 
"const GENERIC = true;" 
to 
"const GENERIC = false;" 
, then save the file and run the "npm run update_base_uri" , it should update the tokens.

**Comment by codeSTACKr** [comment]
Running `npm run update_base_uri` will reveal all NFTs. No matter if they are presale minted or minting during public sale. You only need to run this once. After that all mints will be revealed automatically. (You will need to hit the refresh button on the NFT on OpenSea to refresh the metadata there for any that are not revealed. You will not have to do that for any minted after reveal.)

**Comment by Unprecedentedclub** [comment]
I open sea I had a discussion they are telling since it has not being mint it will not show. So please support on the same.
