### ISSUE TITLE
ipfs upload failed

### ISSUE THREAD

**Issue by Dacooa** [codeSTACKr/minter-dapp#15]
When I run 
npm run upload_files
I get

![Screenshot (20)](https://user-images.githubusercontent.com/102386435/161441788-c6d44daf-bcc9-4734-9fbf-b2a5a65a8e05.png)

**Comment by jaydwivedi12** [comment]
In headers add Authorization and API it will solve your problem

**Comment by galagenixmedia** [comment]
> In headers add Authorization and API it will solve your problem

Hi, would like to ask where is the headers to add authorization and API

**Comment by codeSTACKr** [comment]
Your API key is not saved in the .env file.
