### ISSUE TITLE
Spinner with no text  - Is this a MetaMask issue? 

### ISSUE THREAD

**Issue by edhellerdotcom** [codeSTACKr/minter-dapp#16]
If a first time user (without metamask) opens this shop in a browser, or if I open it in an incognito browser, 
we will get the spinner graphic, but without any of the "Welcome" and "Connect to MetaMask to Get Started" text.

Am I missing something in my code? Is something up with how the metamask is integrated?

I want to make it as easy as possible for a first time visitor to connect to metamask. 

Here's the location of the shop I'm troubleshooting: 
https://realdeepdish.netlify.app/
and the repository fork I'm working in : 
https://github.com/edhellerdotcom/minter-dapp 

Would appreciate some help if anyone has any thoughts. Thanks.

**Comment by jaydwivedi12** [comment]
I think this is not metamask issue . This is because of frontend folder . Work in it.

**Comment by edhellerdotcom** [comment]
I'm thinking it could be one of those:  

if "metamask extension is installed, but not connected" 
then "show the rest of the connection text" 

situations, but I don't know the code well enough to find the place to tell it to 

if "metamask is NOT installed"
then "show the text anyway."

Any ideas where to find this code?

Thanks for the help.

**Comment by jaydwivedi12** [comment]
metamask_onboarding.js it could be there.

**Comment by edhellerdotcom** [comment]
I haven't dived into the .js file mentioned above, but I confirmed that one of the elements in the style.css under the /* NOT CONNECTED */ section was preventing the text from being visible. I appear to have resolved that by commenting out the 'opacity' and 'transform:' variables.

The spinner being a main visual element on the page can be a bit confusing for first time visitors, btw. Is there a way to replace that spinner with another image?

**Comment by astrosocietyxyz** [comment]
I think I found the solution!

 I would like to add that I have no coding experience prior to watching CodeSTACKr videos 1000x and trying to study the codes. 

After playing around with the front end
after line 55 in frontend/ app.js

I added

***line 56**
          // HIDE SPINNER
          spinner.classList.add('hidden');
          notConnected.classList.remove('hidden');
          notConnected.classList.add('show-not-connected');


Did not add or change anything else.

Hope this helps or brings you a step closer to how you want your website to looks.

Cheers,
Michael

**Comment by jaydwivedi12** [comment]
I want to remove that spinner and add another graphics. spinner is not so attractive at all.

Any idea or Suggestion,

**Comment by astrosocietyxyz** [comment]
Have you tried changing the colors of the spinner? Maybe that would change your opinion on it.

**Comment by jaydwivedi12** [comment]
Hey do you have any idea that 
how to transfer sales funds from smart contract to wallet??

**Comment by jaydwivedi12** [comment]
![Screenshot_2022-04-15-21-55-25-548_io metamask](https://user-images.githubusercontent.com/85431207/163595915-a04f8a11-9fd6-4a87-851c-bb517b34a133.jpg)
![Screenshot_2022-04-15-21-39-10-890_io metamask](https://user-images.githubusercontent.com/85431207/163595922-858d1f41-825b-408a-99f2-528741a4ab98.jpg)
After connecting metamask in metamask browser in android . Presale box doesn't appear this is kept loading like this .. i have tried with other website also same issue to all browser.

**Comment by codeSTACKr** [comment]
Spinner with no text is a Netlify configuration issue. Be sure you set the base path to `frontend` and saved your API key in the environment variables.

**Comment by edhellerdotcom** [comment]
Where do I add that code? In the index.html?

**Comment by notMayhem** [comment]
> Spinner with no text is a Netlify configuration issue. Be sure you set the base path to `frontend` and saved your API key in the environment variables.

Ive done this correctly and im having the same issue still...that isnt the cause.....

**Comment by lilgoat347** [comment]
does anyone have a solution to this problem?
