### ISSUE TITLE
Upload_metadata : Error 502

### ISSUE THREAD

**Issue by wazir09** [codeSTACKr/minter-dapp#2]
Hello Jesse
quick question. I encounter a problem when i'm uploading  the metadata files. it says :
CATCH ERROR: ERROR STATUS: 502
Retrying
CATCH ERROR: FetchError: request to https://api.nftport.xyz/v0/metadata/directory failed, reason: socket hang up.

i would appreciate any help. thanks so much

**Comment by NFTKing11** [comment]
Hello Jesse
i have also the same Problem
i would appreciate any help.  Thanks in advance

**Comment by lizee78** [comment]
Ok you need to add your nft port api key from .env example by copying the
env file and pasting it or do it like this duplicate it by copying the file
and pasting it, then add your api key the one you got from nft port I hope
this will solve the problem. 😉

**Comment by wazir09** [comment]
Hi Lizee78,

Thanks for the suggestion. I did that already as per the video instruction. I find out that if i reduce the collection size from 10k to 1k nft, I'm able to upload the metadata. Which could be possible, as I'm only using the free package and maybe hit the limit. If that is the case, i don't mind to get the monthly package, I'm just afraid that when i change the plan to the monthly paid plan, the issue still happen with a larger collection.

**Comment by thepeanutgalleryandco** [comment]
@wazir09 a new release was made that will fix the 502 issue. Please update your repo to make use of the fix and try again.

**Comment by lizee78** [comment]
Did you have this problem running the Presale, that is npm run presale
