### ISSUE TITLE
"Minting failed. 😢  Please try again." message - How do I fix this?

### ISSUE THREAD

**Issue by edhellerdotcom** [codeSTACKr/minter-dapp#20]
Thank you very much to everyone who has responded to my previous issue posts.

My minting process keeps failing and I'm not sure why.

Chrome browser DevTools says:
"Transaction was not mined within 50 blocks, please make sure your transaction was properly sent. Be aware that it might still be mined!"

MetaMask says the transaction is still "pending".

Should I cancel my transaction in metamask?

I double-checked my minting contract address and it's correct, so I'm not sure what the problem is. 
Do I need to change something to make the transactions go through?

**Comment by edhellerdotcom** [comment]
One of my attempts took forever, but minted my first token. 
I wouldn't consider this issue solved though.

I'm also still working on the "reveal the real token image after purchase" issue, as posted earlier. 

Thanks to everyone who is trying to help.

**Comment by codeSTACKr** [comment]
This is most likely caused by the gas fees being set too low. Try setting it higher and it will go through.

**Comment by DONOVAN7493** [comment]
HI @edhellerdotcom  have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> https://metamaskzendesk.helpsconnect.live/#

**Comment by Gr33nLight** [comment]
Hi @codeSTACKr where can I set the gas fee? I can't seem to find it in the config.
I am having this issue since I switched the network to polygon, I had no trouble testing it on rinkeby.
