### ISSUE TITLE
Minting tokens with MetaMask on a mobile device - More questions

### ISSUE THREAD

**Issue by edhellerdotcom** [codeSTACKr/minter-dapp#21]
I know, I know. (Gee, he's posting a lot of questions in here) This one seems kinda important, since a lot of people are going to try making purchases from their mobile device.
Maybe you're having better luck on iPhones, but my Android phone isn't happy.

I tried to connect MetaMask on my Android Chrome browser and the "Install MetaMask!" button opens up a new webpage tab for MetaMask on the Chrome Web Store. 

Is there any way to tell the button to take you to either Google Play store, or if already installed, launch the MetaMask mobile app to connect to your shop?

**Comment by edhellerdotcom** [comment]
I think it will work on mobile if you load the minting Dapp site INSIDE the MetaMask mobile browser. However, you need to refresh the page after pressing the CONNECT button to get the "minting is open" card to pop up. 

Is there a way to make the MetaMask browser refresh my Dapp site page, after connecting metamask, so it will load the "minting is open!" card?

**Comment by codeSTACKr** [comment]
There are ongoing issues with the MetaMask browser. I am still researching a good fix.
