### ISSUE TITLE
Cannot close minting UI box on the webpage

### ISSUE THREAD

**Issue by krupis** [codeSTACKr/minter-dapp#23]
I have deployed a webserver as explained in the guide. When I connected to my metamask, whenever I refresh the page, the website automatically opens up a minting box:
![image](https://user-images.githubusercontent.com/22237034/162020031-ecfeef00-7b39-44de-bd7e-b9ee5787481f.png)

Is there any way to only open this when a button "MINT" is pressed? 

Also, there seems to be no way to close it. It just stays there permamently.

**Comment by codeSTACKr** [comment]
That is working as intended. If minting is open, then that box will appear.
