### ISSUE TITLE
I can't get this to run generate anymore for my finalize collection

### ISSUE THREAD

**Issue by Dacooa** [codeSTACKr/minter-dapp#25]
I don't know where to even star
![Screenshot (22)](https://user-images.githubusercontent.com/102386435/162069501-e2507a47-35bd-4a74-8ef3-5396dc6fa98e.png)
t

**Comment by codeSTACKr** [comment]
The `path` issue is a result of either your configuration not being correct, not saved, or your layer folder/file names containing special characters. For the names, you should only use a-z, 0-1, and spaces. Do not use dashes, slashes, or any other special characters.

**Comment by Dacooa** [comment]
it ended up being a NFTport issue but thank you everyone.

**Comment by Dacooa** [comment]
I got it fix. Thank you everyone.
