### ISSUE TITLE
npm run upload_files gets stuck/paused part way thru...

### ISSUE THREAD

**Issue by PencilsDown** [codeSTACKr/minter-dapp#27]
Hello, i have successfully followed the steps to generate images and prep the consig.js file, and have generated 2500 images, but when running "npm run upload_files" it gets stuck/paused at #335...thoughts? greatly appreciated! the video has been very clear and helpful...

![image](https://user-images.githubusercontent.com/102769859/162333954-19eef06a-357e-43cd-ba98-d8e69bde1144.png)

**Comment by jaydwivedi12** [comment]
Close the terminal and again run npm run upload_files.
It will upload file where you last left off.

**Comment by codeSTACKr** [comment]
Could be an internet connection issue. If it gets stuck, you can start it over and it will pick up where it left off.
