### ISSUE TITLE
Still new to GitHub - Is there a way to start a new minting while the current one is still on?

### ISSUE THREAD

**Issue by edhellerdotcom** [codeSTACKr/minter-dapp#28]
Still new to GitHub, so maybe there's a simple solution I'm not seeing - 
Is there a way to duplicate the fork I made (series 1), or make a second fork of this repo,  so I can start a new (series 2) minting dApp while the previous one is still up and running (hasn't minted all it's coins yet)?

I want to make a new set of NFTs that I'm going to mint all at once.

**Comment by codeSTACKr** [comment]
You can create multiple "branches" on your forked repo. You can the switch between branches, and each can have different settings and files.
