### ISSUE TITLE
Cannot be whitelisted

### ISSUE THREAD

**Issue by ericksommet** [codeSTACKr/minter-dapp#29]
Hi I managed to make it to the whitelisting of your one's own address to try the minting process (48:08 mn of the video) and the contract gets updated without a problem.
 Now when I go back to my Netlify site to refresh the page I still dont get whitelisted.  My account number is correctly between quotes so I really dont know what is up.
When I do this I am on the rinkeby part of y wallet, if I change that to ethereum main the waiting gif keeps turning without ever landing me anywhere...could that be the issue?

**Comment by shusmush** [comment]
You need to be patient when the whitelist addresses are updated. can take a while on Rinkby (happened with me)

**Comment by codeSTACKr** [comment]
It could take some time to update, but you can also check to be sure the whitelisted addresses were saved properly here: https://docs.nftport.xyz/docs/nftport/b3A6NDE1MTQ2MzI-list-all-your-deployed-collection-contracts

**Comment by ericksommet** [comment]
actually the problem was that I was trying to mint ahead of my presale date so it would not work (dah)...changed the date and it worked.   Newbie mistake..Thanks for answering anyhow.
Erick
    On Friday, April 15, 2022, 07:05:00 AM GMT-5, shusmush ***@***.***> wrote:  
 
 


You need to be patient when the whitelist addresses are updated. can take a while on Rinkby (happened with me)
