### ISSUE TITLE
error Missing script: "generate"

### ISSUE THREAD

**Issue by StartUpDream** [codeSTACKr/minter-dapp#3]
error Missing script: "generate"

**Comment by draczer01** [comment]
could you please elaborate so I can replicate the issue?

**Comment by ericksommet** [comment]
same problem... even in the very first trial with the cats..  npm run generate is answered by an error warning saying missing script Generate. Tried to install the 3 NPM extensions> support, command and scripts ...but no results

**Comment by ericksommet** [comment]
didnot have that problem with the V1.01 of your code.

**Comment by codeSTACKr** [comment]
just be sure you are in the `backend` folder in your terminal before running the command.
