### ISSUE TITLE
Sync Changes does not work even thoug I forked tho project in the beginning  

### ISSUE THREAD

**Issue by mdamarx** [codeSTACKr/minter-dapp#30]
I don't know what to do...
After committing the changes I tried to sync them and it takes forever.
I forked the project, I'm logged in in GitHub, I trust the GitHub extension, I just don't know what the issue could be. 
After committing the changes I had to run 

git config --global user.email "mail address"
git config --global user.name "username"

but after running this I was able to start the sync process so it should have worked...correct?

**Comment by MetaAshMCP** [comment]
I wish I was a programmer to help you...I had to restart Visual Code. I
made sure i was logged in to Github, and copied and pasted the github code
which CodeStakr uploaded (there is a new release version...try downloading
that one in the RELEASE tab to the right?)

**Comment by Shearlling** [comment]
same had happened to me and after pushing all changes deploying the website did not work, i juts got codestacker website template which i updated it with my own domain through netlify and any changes i apply on VS not reflecting there, and i have no clue where the data i push goes??

**Comment by Shearlling** [comment]
what i had noticed that the "Go Live" bottom sign is not there on my VS all the time its not there

**Comment by codeSTACKr** [comment]
It should sync with your forked repo which will be listed in your repositories on GitHub under your profile.
