### ISSUE TITLE
Simple question from a simple one!

### ISSUE THREAD

**Issue by shusmush** [codeSTACKr/minter-dapp#33]
How to I access/withdraw the sales funds in the wallet when minting starts?

**Comment by jaydwivedi12** [comment]
Exactly same question i have  . How to transfer funds from smart contract to wallet.

**Comment by shusmush** [comment]
Sorted!!!
Go to etherscan/polscan
get contract address, and connect ur 'treasury' wallet to it and then go to WRITE CONTRACT, and open WITHDRAW FEES.. and hey presto... Amazing and thank you Jesse
