### ISSUE TITLE
Transfer Funds

### ISSUE THREAD

**Issue by jaydwivedi12** [codeSTACKr/minter-dapp#34]
How to transfer sales funds from smart contract to your wallet??

**Comment by shusmush** [comment]
Sorted!!!
Go to etherscan/polscan
get contract address, and connect ur 'treasury' wallet to it and then go to WRITE CONTRACT, and open WITHDRAW FEES.. and hey presto... Amazing and thank you Jesse

**Comment by codeSTACKr** [comment]
👍
