### ISSUE TITLE
Cannot use project

### ISSUE THREAD

**Issue by samtrez** [codeSTACKr/minter-dapp#4]
Little bit of context -- when I attempt to use the clone repository method to use this project the button in VSCode has no reaction so I can't actually paste the link to use it.

So I've downloaded and unzipped the folder and when I try to install and run I am return these messages:

<img width="804" alt="Screen Shot 2022-03-23 at 1 07 27 AM" src="https://user-images.githubusercontent.com/102201902/159622746-343ca8fc-de86-4ad7-a3ad-6c766ef4d240.png">

**Comment by draczer01** [comment]
run `cd backend` and then `npm i` after that you should be able to run `npm run generate`
