### ISSUE TITLE
npm run upload_metadata times out and failes with 502 error

### ISSUE THREAD

**Issue by HabedyOmid** [codeSTACKr/minter-dapp#5]
I noticed when uploading Images and MetaData json files the API request is not using the Authorization header when sending request to NFTPort API endpoint. 

I wonder how come i was able to upload  images using `npm run upload_files ` command without any issue, but `run upload_metadata` cause TIME_OUT error and after Retrying it throws 502 error. 

I noticed both `/utils/nftport/uploadFiles.js` and `/utils/nftport/uploadMetas.js` are not using NFTPort API key, its an empty object for both files. so my qustion is do we need the NFTport API key to upload files, if so, why images were uploaded without API key and why metadata json files are not uploading. 

By the way i am trying to upload a collection 5000 json files, and `_metadata.json` file already exist with information for all 5000 metadata along with 5000 metadata.json files under `/build/json/0.json - 4999.json `files.
<img width="474" alt="Screen Shot 2022-03-24 at 11 11 51 PM" src="https://user-images.githubusercontent.com/18051737/160053757-05a244e1-7c6a-4ad7-b40e-975de438b9fc.png">

**Comment by TinoJHB** [comment]
Did you manage To get any Fix? I'm facing the same challenge... We may be the First 2.

**Comment by roshiend** [comment]
I have got same issue. you guys are not alone. looking for solution tbh

**Comment by roshiend** [comment]
tremendous. I will have a look.  :)

**Comment by jaydwivedi12** [comment]
is it works for you.I also got same kind of error 403 even after adding API ?

**Comment by PencilsDown** [comment]
Thank you @HabedyOmid, I had the same issue and your fix worked!
