### ISSUE TITLE
[Bug]: Netlify Site Partially Loads...

### ISSUE THREAD

**Issue by PencilsDown** [codeSTACKr/minter-dapp#50]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

i have seemingly been successful with deploying a contract, but when i get to the stage of testing out the dapp on the URL via netlify, i was first able to see the pre-written "CodeCats" text and images, but then shortly i received the below loading screen.  This has continued to load for over a day, even upon reboot and deleting the site thru netlify, and going thru the steps again to paste in the nftport key, etc....

![image](https://user-images.githubusercontent.com/102769859/164568519-3caa1304-a5cf-4f2d-a47f-d1b22988d5ea.png)

### What have you tried?

I Googled and tried to ask the community in the discord server but was not able to post a question of find a solution.

### Protect your information

- [X] I Agree

**Comment by peazley** [comment]
What browser are you using?

**Comment by PencilsDown** [comment]
@peazley using chrome, but no luck on MS edge either

**Comment by peazley** [comment]
Hmm. I have a similar issue using Safari on MacOS, but not having any issues with Chrome.
