### ISSUE TITLE
[Bug]: CATCH ERROR: ERROR STATUS: 404

### ISSUE THREAD

**Issue by THEgoatSOCIAL** [codeSTACKr/minter-dapp#64]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

When trying to update the presale mint date after confirming 'y' it comes up with CATCH ERROR: ERROR STATUS: 404 and not contract updated and ideas on how to fix?

### What have you tried?

I Googled and asked the community in the discord server but could not find a solution..

### Protect your information

- [X] I Agree

**Comment by ChrisX33** [comment]
I have the same issue described above

```
Updating presale_mint_start_date to 2022-05-12T16:20:00+01:00, correct? (y/n): y
CATCH ERROR: ERROR STATUS: 404
PS C:\Users\chris\Desktop\NFT ART Contracts\NewMinterDapp\minter-dapp\backend> 
```
