### ISSUE TITLE
npm run upload_files stops uploading 

### ISSUE THREAD

**Issue by BillionaireCartel** [codeSTACKr/minter-dapp#8]
I have attempted this 4 times already. Everytime I run the npm run upload_files the terminal runs it and it will stop randomly. I am not able to add another command. Has anyone else experienced this and found a resolution?

**Comment by jaydwivedi12** [comment]
same here it shows error 403

**Comment by PencilsDown** [comment]
same here ...mine stopped randomly as well and then upon reboot it appears to forget all of the npm commands...no solution yet

![image](https://user-images.githubusercontent.com/102769859/162342246-0eab44ee-e106-4c24-9ce6-08d224afb877.png)

**Comment by codeSTACKr** [comment]
403 indicates an authorization issue. That would most likely relate to your API key.

If you look internet connection, the upload could stop. In that case you can press `Ctrl/Cmd+C` to stop the process then restart it when you have internet again. It will pick up where it left off.
