### ISSUE TITLE
contract limit exceeded on rinkeby

### ISSUE THREAD

**Issue by ericksommet** [codeSTACKr/minter-dapp#9]
Hi, this is what I get when I deploy the contract:

PS C:\Users\User\Documents\Erick\NFT\minter-dapp\backend> npm run deploy_contract

> minter-dapp-backend@0.0.1 deploy_contract
> node utils/nftport/deployContract

Is all REQUIRED contract information correct in config.js? (y/n): y
CATCH ERROR: NOK: Contract limit exceeded on rinkeby

Any help would be wonderfull
Thanks

**Comment by codeSTACKr** [comment]
You've created your limit of contracts. You can check your deployed contracts here: https://docs.nftport.xyz/docs/nftport/b3A6NDE1MTQ2MzI-list-all-your-deployed-collection-contracts
